version: '3.8'
services:
  backend:
    build: ./backend
    image: backend-app:latest
    container_name: backend-app
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    image: frontend-app:latest
    container_name: frontend-app
    ports:
      - "3000:3000"
    restart: always

